import Head from 'next/head';
import { Nunito, Nunito_Sans } from '@next/font/google';
import classNames from 'classnames';
import ButtonOutlinedRounded from '@/components/button-outlined-rounded';
import { Header } from '@/components/header';
import ButtonGradient from '@/components/button-gradient';
import Link from 'next/link';
import ArrowRightSVG from '@/svgs/arrow-right-svg';
import CoffeeAndCroissantSVG from '@/svgs/coffee-and-croissant-svg';

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '800', '900'],
  variable: '--font-nunito',
  display: 'auto',
});

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-nunito-sans',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={classNames(
          nunito.variable,
          nunitoSans.variable,
          'flex items-center justify-center h-screen main-bg',
        )}
      >
        <div className="fixed top-0 left-0 bg-black/30 p-2">
          <div>
            <span className="text-stone-300 text-xs font-sans">
              Created and designed by:{' '}
            </span>
            <Link
              href="https://dribbble.com/Mansoor-Gull"
              className="text-stone-100 text-xs font-sans"
            >
              {'Mansoor'}
            </Link>
          </div>
          <div>
            <span className="text-stone-300 text-xs font-sans">
              Developed by:{' '}
            </span>
            <Link
              href="https://github.com/nickmarca"
              className="text-stone-100 text-xs font-sans"
            >
              {'Nick Marca'}
            </Link>
          </div>
        </div>
        <div className="w-[68rem] h-[44rem] bg-gray-100 rounded-xl component-card flex overflow-hidden min-w-[1020px]">
          <div className="w-3/4 flex flex-col">
            <div className="px-24 py-12 flex-1">
              <Header />
              <div className="pr-20">
                <div className={classNames(styles.headerContainer)}>
                  <h1 className={classNames(styles.header)}>
                    <span className="text-6xl">{`Hungry?`}</span>
                    {` let’s make a yummy breakfast`}
                  </h1>
                </div>
                <p className="font-sans text-stone-500/75 font-semibold mt-2 leading-5">
                  A game of taste we make healthy and yummy breakfast with home
                  deliver in seconds at north
                </p>
                <div className="mt-16 flex gap-10">
                  <ButtonGradient>{'Order Now'}</ButtonGradient>
                  <Link
                    className="font-sans font-semibold text-sm text-stone-700 leading-10"
                    href="/"
                  >
                    <span>{'Tour our kitched'}</span>
                    <ArrowRightSVG className="inline fill-stone-700 mt-[-1px]" />
                  </Link>
                </div>
              </div>
            </div>
            <div className="px-48 py-16 border-t-2 border-stone-200/85 flex">
              <div className="flex-1 flex justify-center border-r-2 border-stone-200">
                <div>
                  <h3 className="font-sans font-semibold text-lg text-stone-700">
                    {'40+ Breakfasts'}
                  </h3>
                  <p className="font-sans text-xs text-stone-500/75">
                    {'most delicious'}
                  </p>
                </div>
              </div>
              <div className="flex-1 flex justify-center">
                <div>
                  <h3 className="font-sans font-semibold text-lg text-stone-700">
                    {'Home Delivery'}
                  </h3>
                  <p className="font-sans text-xs text-stone-500/75">
                    {'in town only'}
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="w-1/4 bg-[url('/breakfasto/img/side-bg.svg')] bg-cover flex flex-col items-center p-8 relative">
            <ButtonOutlinedRounded>{'Log In'}</ButtonOutlinedRounded>
            <CoffeeAndCroissantSVG className="absolute top-36 right-20" />
          </div>
        </div>
      </main>
    </>
  );
}

const styles = {
  headerContainer: [
    'mt-20',
    'relative',
    'before:w-20',
    'before:h-20',
    'before:rounded-full',
    'before:absolute',
    'before:bg-[#FFE7EA]',
    'before:z-0',
    'before:translate-x-[-50%]',
  ],
  header: [
    'font-serif',
    'text-comet',
    'text-4xl',
    'font-extrabold',
    'z-10',
    'relative',
  ],
};
